version: '3.8'

services:
  web:
    build: .
    container_name: educative_games_app
    ports:
      - "5000:5000"
    volumes:
      # Pujem la persistència del json fora del contenidor cap al host
      # d'aquesta forma no perdem dades de puntuació si el destuïm
      - ./data:/app/data
    restart: always
