version: '3.8'

services:
  web:
    build: .
    container_name: educative_games_app
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: ${MONGODB_URI:-}
      MONGODB_DB_NAME: ${MONGODB_DB_NAME:-educative_games}
      MONGODB_COLLECTION: ${MONGODB_COLLECTION:-game_scores}
    volumes:
      - ./data:/app/data
    restart: always
